Added Message for mateksys_PMW3901_VL53L0X
paparazzi/pprzlink pull request #137
Opened 2021-01-12 09:50 UTC by pcampolucci

Sensor implemented in paparazzi (https://github.com/paparazzi/paparazzi/pull/2639) requires message in messages.xml file to show the data on logger. 

New message uses slot of no longer used message.

2021-01-29 12:48 UTC, gautierhattenberger commented
There are already 3 optical flow related messages. Would it be possible to merge some of them ? I think the closest to this one is the PX4FLOW. It can be updated  for a more generic name and correct field types.

2021-01-30 14:51 UTC, pcampolucci commented
PX4 message and MATEKFLOW very very similar indeed. I have merged and tested them. It should be good now.

2021-01-30 15:50 UTC, gautierhattenberger requested changes

2021-01-30 15:50 UTC, gautierhattenberger commented on message_definitions/v1.0/messages.xml
> -
this message is actually used here: https://github.com/paparazzi/paparazzi/blob/master/sw/airborne/modules/multi/rssi.c#L65
so we have to keep it
may be update the comment with `TODO merge with XTEND_RSSI`

2021-01-30 16:44 UTC, gautierhattenberger approved these changes

2021-01-30 16:44 UTC, merged